import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { slices } from '../src/model.js';

await mkdir('.checks', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || (process.platform === 'win32' ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : undefined), headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 950 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const url = process.env.CHECK_URL || 'http://127.0.0.1:5173/';
const storage = () => page.evaluate(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')));
const click = name => page.getByRole('button', { name, exact: true }).click();
const edit = () => page.getByRole('link', { name: 'Edit', exact: true }).click();
const present = () => page.getByRole('link', { name: /^Present/ }).click();
try {
  await page.goto(url);
  assert.equal(await page.title(), 'Nawras Spinner.');
  assert.equal((await storage()).wheels[0].options.length, 8);
  await page.screenshot({ path: '.checks/library.png', fullPage: true });
  await edit();
  await page.getByLabel('Wheel title', { exact: true }).fill('Event Activities');
  await page.getByLabel('Option 1 label', { exact: true }).fill('Wordle Challenge');
  await page.getByLabel('Option 1 label', { exact: true }).blur();
  await page.getByLabel('Adjust weight', { exact: true }).nth(0).check();
  await page.getByLabel('Option 1 weight', { exact: true }).fill('2.5');
  await page.getByLabel('Option 1 weight', { exact: true }).blur();
  await page.getByLabel('Link', { exact: true }).nth(0).check();
  await page.getByLabel('Option 1 URL', { exact: true }).fill('javascript:alert(1)');
  assert.equal(await page.locator('.slice-link').count(), 0);
  await page.getByLabel('Option 1 URL', { exact: true }).fill('https://example.com/game');
  await page.getByLabel('Option 1 URL', { exact: true }).blur();
  assert.equal(await page.locator('.slice-link').getAttribute('rel'), 'noopener noreferrer');
  await context.route('https://example.com/**', route => route.fulfill({ body: '<h1>Test link</h1>', contentType: 'text/html' }));
  const popupPromise = page.waitForEvent('popup'); await page.locator('.slice-link').click();
  const popup = await popupPromise; await popup.waitForLoadState();
  assert.equal(popup.url(), 'https://example.com/game');
  assert.equal(await popup.evaluate(() => window.opener === null), true); await popup.close();
  await page.reload();
  assert.equal(await page.getByLabel('Wheel title', { exact: true }).inputValue(), 'Event Activities');
  assert.equal(await page.getByLabel('Option 1 weight', { exact: true }).inputValue(), '2.5');
  await page.getByLabel('Adjust weight', { exact: true }).nth(0).uncheck();
  assert.equal((await storage()).wheels[0].options[0].weight, 1);
  await click('Undo'); assert.equal((await storage()).wheels[0].options[0].weight, 2.5);
  await click('Redo'); assert.equal((await storage()).wheels[0].options[0].weight, 1);
  await click('Clear Options'); await page.getByRole('button', { name: 'Clear Options', exact: true }).last().click();
  await page.waitForFunction(() => document.querySelectorAll('.option-row').length === 0);
  await click('Undo'); assert.equal((await storage()).wheels[0].options.length, 8);
  await click('Clear Options'); await page.keyboard.press('Escape');
  assert.equal((await storage()).wheels[0].options.length, 8);
  await click('Paste list');
  await page.getByLabel('Options, one per line').fill('Alice\nBob\nCara\nDina\nEli'); await click('Add Options');
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')).wheels[0].options.length === 13);
  await click('Undo');
  await click('+ Add option');
  assert.equal(await page.getByRole('button', { name: 'Redo', exact: true }).isEnabled(), false);
  await click('Undo');
  await page.getByLabel('Adjust weight', { exact: true }).nth(0).check();
  await page.getByLabel('Option 1 weight', { exact: true }).fill('2.5');
  await page.getByLabel('Option 1 weight', { exact: true }).blur();
  assert.equal(await page.locator('.chance').first().textContent(), '26.32%');
  await page.screenshot({ path: '.checks/editor.png', fullPage: true });
  await present();
  await page.screenshot({ path: '.checks/audience.png', fullPage: true });
  assert.equal(await page.getByLabel('Option 1 label', { exact: true }).count(), 0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await click('Spin');
  assert.equal(await page.locator('#dialog').isVisible(), false);
  assert.equal(await page.locator('.slice-link').count(), 0);
  assert.equal(await page.getByRole('button', { name: /Spinning/ }).isEnabled(), false);
  await page.locator('#dialog').waitFor({ state: 'visible', timeout: 8500 });
  const winner = await page.locator('.winner-content h2').textContent();
  const spinData = (await storage()).wheels[0];
  const angle = await page.locator('.wheel-disc').evaluate(el => Number(el.style.transform.match(/rotate\(([^d]+)deg\)/)[1]));
  const pointer = (360 - angle % 360) % 360;
  const pointed = slices(spinData.options).find(s => pointer >= s.start && pointer < s.end);
  assert.equal(pointed.item.label, winner);
  await page.locator('.winner-controls').waitFor({ state: 'visible' });
  await page.screenshot({ path: '.checks/winner.png', fullPage: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await click('Close winner'); await page.getByRole('button', { name: /Back$/ }).click();
  await page.getByRole('link', { name: 'My Wheels', exact: true }).last().click();
  await click('Duplicate Event Activities');
  let wheels = (await storage()).wheels; assert.equal(wheels.length, 2); assert.notEqual(wheels[0].options[0].id, wheels[1].options[0].id);
  const exportedPromise = page.waitForEvent('download'); await page.getByRole('button', { name: /Export$/ }).click();
  const exported = await exportedPromise; const exportData = JSON.parse(await readFile(await exported.path(), 'utf8'));
  await page.locator('#import-file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exportData)) });
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')).wheels.length === 4);
  wheels = (await storage()).wheels; assert.equal(new Set(wheels.map(w => w.id)).size, 4);
  const beforeInvalid = JSON.stringify(await storage());
  await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":2,"wheels":[]}') });
  await page.getByRole('status').filter({ hasText: 'Import failed' }).waitFor(); assert.equal(JSON.stringify(await storage()), beforeInvalid);
  await click('+ Create Wheel');
  await page.getByLabel('Wheel title', { exact: true }).fill('Top Five');
  await click('Paste list'); await page.getByLabel('Options, one per line').fill('Alice\nBob\nCara\nDina\nEli'); await click('Add Options');
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')).wheels.find(w => w.title === 'Top Five').options.length === 5);
  await page.reload(); assert.equal((await storage()).wheels.find(w => w.title === 'Top Five').options.length, 5);
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: '.checks/mobile-editor.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await click('Clear Options'); await page.getByRole('button', { name: 'Clear Options', exact: true }).last().click();
  await page.waitForFunction(() => document.querySelectorAll('.option-row').length === 0);
  await click('+ Add option'); await page.getByLabel('Option 1 label', { exact: true }).fill('A very long winning option label that remains complete in the winner popup');
  await page.getByLabel('Link', { exact: true }).check(); await page.getByLabel('Option 1 URL', { exact: true }).fill('https://example.com/winner');
  await page.getByLabel('Remove winners during presentation').check();
  await present(); await click('Spin'); await page.locator('#dialog').waitFor({ state: 'visible' });
  assert.equal(await page.getByRole('button', { name: 'Spin Again', exact: true }).isEnabled(), false);
  assert.equal(await page.getByRole('link', { name: /Open Link/ }).getAttribute('href'), 'https://example.com/winner');
  const empty = (await storage()).wheels.find(w => w.title === 'Top Five'); assert.equal(empty.options.length, 1);
  await click('Close winner'); assert.equal(await page.getByRole('button', { name: 'Spin', exact: true }).isEnabled(), false);
  await page.reload(); assert.equal(await page.getByRole('button', { name: 'Spin', exact: true }).isEnabled(), true);
  await page.evaluate(() => localStorage.setItem('nawras-spinner:v1', 'damaged-data')); await page.reload();
  await click('+ Create Wheel'); await page.getByLabel('Wheel title', { exact: true }).fill('Protected');
  assert.equal(await page.evaluate(() => localStorage.getItem('nawras-spinner:v1')), 'damaged-data');
  assert.equal(await page.locator('#saved').textContent(), 'Not saved');
  await page.evaluate(() => localStorage.setItem('nawras-spinner:v1', JSON.stringify({ version: 1, wheels: [] }))); await page.goto(url); await page.reload();
  assert.equal(await page.locator('.card').count(), 0);
  await page.evaluate(() => localStorage.removeItem('nawras-spinner:v1')); await page.reload();
  await click('Delete Nawras Activities'); await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal((await storage()).wheels.length, 1);
  await click('Delete Nawras Activities'); await click('Delete');
  await page.waitForFunction(() => document.querySelectorAll('.card').length === 0);
  await page.reload(); assert.equal((await storage()).wheels.length, 0);
  await click('+ Create Wheel'); await click('Paste list');
  await page.getByLabel('Options, one per line').fill(Array.from({ length: 100 }, (_, i) => `Player ${i + 1}`).join('\n')); await click('Add Options');
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')).wheels[0].options.length === 100);
  assert.equal(await page.locator('.slice-label').count(), 0);
  await present(); await click('Spin'); await page.locator('#dialog').waitFor({ state: 'visible' });
  assert.match(await page.locator('.winner-content h2').textContent(), /^Player \d+$/);
  const deniedContext = await browser.newContext();
  await deniedContext.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw Error('Storage denied'); } }));
  const denied = await deniedContext.newPage(); denied.on('pageerror', error => errors.push(error.message));
  await denied.goto(url); await denied.getByRole('button', { name: '+ Create Wheel', exact: true }).click();
  await denied.getByLabel('Wheel title', { exact: true }).fill('Without storage');
  assert.equal(await denied.locator('#saved').textContent(), 'Not saved'); await deniedContext.close();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: editing, persistence, history, weighted pointer, links, removal, JSON transfer, empty state, damaged storage and mobile layout.');
} finally { await browser.close(); }

