import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultColor } from '../src/colors.js';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || (process.platform === 'win32' ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : undefined), headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
const url = process.env.CHECK_URL || 'http://127.0.0.1:4175/';
const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')));
const click = name => page.getByRole('button', { name, exact: true }).click();
const setColor = async (number, value) => {
  const picker = page.getByLabel(`Option ${number} color`, { exact: true });
  await picker.focus(); await picker.fill(value); await picker.dispatchEvent('input'); await picker.blur();
};
try {
  await page.goto(url); await page.getByRole('link', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Option 1 color', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await page.locator('input[type=color]').count(), 8);
  const original = (await saved()).wheels[0];
  await setColor(1, '#101020'); await setColor(2, '#fafafa');
  assert.equal(await page.locator('.slice-label').nth(0).evaluate(el => getComputedStyle(el).fill), 'rgb(255, 255, 255)');
  assert.equal(await page.locator('.slice-label').nth(1).evaluate(el => getComputedStyle(el).fill), 'rgb(20, 44, 77)');
  await click('Undo'); assert.equal((await saved()).wheels[0].options[1].color, defaultColor(1));
  await click('Redo'); assert.equal((await saved()).wheels[0].options[1].color, '#fafafa');
  await page.reload(); assert.equal(await page.getByLabel('Option 1 color', { exact: true }).inputValue(), '#101020');
  await page.getByLabel('Option 1 label', { exact: true }).fill('Renamed option');
  await page.getByLabel('Adjust weight', { exact: true }).nth(0).check(); await page.getByLabel('Option 1 weight', { exact: true }).fill('2.5');
  assert.equal((await saved()).wheels[0].options[0].id, original.options[0].id);
  assert.equal((await saved()).wheels[0].options[0].color, '#101020');
  const beforeReset = (await saved()).wheels[0];
  await click('Reset colors');
  const reset = (await saved()).wheels[0]; assert.deepEqual(reset.options.map(o => o.color), reset.options.map((_, i) => defaultColor(i)));
  assert.deepEqual(reset.options.map(({ color, ...o }) => o), beforeReset.options.map(({ color, ...o }) => o));
  await click('Undo'); assert.equal((await saved()).wheels[0].options[0].color, '#101020');
  await click('Redo'); assert.equal((await saved()).wheels[0].options[0].color, defaultColor(0));
  await click('Undo');
  // Delete a preceding entry: color stays with the surviving option, not the index.
  const secondId = (await saved()).wheels[0].options[1].id;
  await click('Remove option 1'); assert.equal((await saved()).wheels[0].options[0].id, secondId); assert.equal(await page.getByLabel('Option 1 color', { exact: true }).inputValue(), '#fafafa');
  await click('Undo');
  await page.getByRole('link', { name: 'My Wheels', exact: true }).last().click();
  const pending = page.waitForEvent('download'); await page.getByRole('button', { name: /Export$/ }).click();
  const exportFile = await pending; const exported = JSON.parse(await readFile(await exportFile.path(), 'utf8'));
  assert.equal(exported.wheels[0].options[0].color, '#101020');
  await page.locator('#import-file').setInputFiles({ name: 'colors.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('nawras-spinner:v1')).wheels.length === 2);
  const imported = (await saved()).wheels[1]; assert.notEqual(imported.options[0].id, original.options[0].id); assert.equal(imported.options[0].color, '#101020');
  await page.goto(`${url}#/edit/${imported.id}`); await page.reload();
  assert.equal(await page.getByLabel('Option 1 color', { exact: true }).inputValue(), '#101020');
  await page.setViewportSize({ width: 320, height: 568 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight && document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await page.locator('.centre-logo').getAttribute('src').then(src => src.endsWith('nawras-circle.png')), true);
  await page.screenshot({ path: '.checks/color-editor-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 900 }); await page.getByRole('link', { name: /^Present/ }).click();
  await page.emulateMedia({ reducedMotion: 'no-preference' }); await click('Spin');
  const timing = await page.locator('.wheel-disc').evaluate(el => el.getAnimations()[0].effect.getTiming());
  assert.equal(timing.duration, 6048);
  assert.equal(await page.locator('.wheel-reflection').evaluate(el => el.getAnimations().length), 0);
  assert.equal(await page.locator('.wheel-labels').evaluate(el => el.getAnimations()[0].effect.getTiming().duration), 6048); assert.equal(await page.getByRole('button', { name: /Spinning/ }).isEnabled(), false);
  assert.equal(await page.locator('#dialog').isVisible(), false);
  await page.locator('.winner-reveal').waitFor({ state: 'visible', timeout: 8000 });
  assert.deepEqual(errors, []); console.log('Color checks passed: live contrast, refresh, color/reset undo-redo, rename/weight/ID stability, JSON transfer, mobile fit, and 6048ms guarded spin.');
} finally { await browser.close(); }
